language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

sudo: false

before_script:
    - COMPOSER_MEMORY_LIMIT=-1 travis_wait composer install --dev --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - travis_retry php vendor/bin/php-coveralls
