services:
    codefog_faq_tags.faq_manager:
        class: Codefog\FaqTagsBundle\FaqManager
        public: true
        arguments:
            - "@codefog_tags.manager.codefog_faq"

    codefog_faq_tags.faq_tag_list_module:
        class: Codefog\FaqTagsBundle\Controller\FrontendModule\FaqTagListModule
        arguments:
            - "@database_connection"
            - "@codefog_faq_tags.faq_manager"
            - "@codefog_tags.manager.codefog_faq"
